#ifndef EI_MODEL_CONFIG_H
#define EI_MODEL_CONFIG_H

// Model configuration
#define EI_CLASSIFIER_SENSOR EI_CLASSIFIER_SENSOR_CAMERA
#define EI_CLASSIFIER_INPUT_WIDTH 96
#define EI_CLASSIFIER_INPUT_HEIGHT 96
#define EI_CLASSIFIER_INPUT_FRAMES 1
#define EI_CLASSIFIER_INPUT_CHANNELS 3
#define EI_CLASSIFIER_INPUT_SIZE (EI_CLASSIFIER_INPUT_WIDTH * EI_CLASSIFIER_INPUT_HEIGHT * EI_CLASSIFIER_INPUT_CHANNELS)

// Model labels
#define EI_CLASSIFIER_LABEL_COUNT 3
#define EI_CLASSIFIER_LABEL_AWAKE "awake"
#define EI_CLASSIFIER_LABEL_NODDING "nodding"
#define EI_CLASSIFIER_LABEL_YAWNING "yawning"

// Model thresholds
#define EI_CLASSIFIER_DETECTION_THRESHOLD 0.65f
#define EI_CLASSIFIER_AWAKE_THRESHOLD 0.60f

#endif // EI_MODEL_CONFIG_H